const tableData = {
    columns: [
        {key: 'name', content: 'Name'},
        {key: 'age', content: 'Age'},
        {key: 'city', content: 'City'},
        {key: 'state', content: 'State'},
        {key: 'pets', content: 'Pets'},
        {key: 'car', content: 'Car'},
        {key: 'job', content: 'Job'},
        {key: 'hobby', content: `Hobby`}
    ],
    rows: [
        {name: 'John', age: '22', city: 'New York', state: 'NY', pets: 'No pets', car: 'Audi', job: 'Developer', hobby: 'Gardening'},
        {name: 'Susan', age: '45', city: 'Los Angeles', state: 'CA', pets: '3 cats', car: 'Honda', job: 'Lawyer', hobby: 'Yoga'},
        {name: 'Luke', age: '34', city: 'Chicago', state: 'IL', pets: '2 dogs', car: 'Ford', job: 'Doctor', hobby: 'Swimming'},
        {name: 'Jack', age: '25', city: 'Houston', state: 'TX', pets: 'No pets', car: 'Chevy', job: 'Teacher', hobby: 'Photography'},
        {name: 'Anna', age: '41', city: 'Philadelphia', state: 'PA', pets: '1 bird', car: 'Toyota', job: 'Engineer', hobby: 'Travelling'},
        {name: 'Tom', age: '19', city: 'San Diego', state: 'CA', pets: '2 hamsters', car: 'BMW', job: 'Accountant', hobby: 'Hiking'},
        {name: 'Alice', age: '38', city: 'Phoenix', state: 'AZ', pets: 'No pets', car: 'Tesla', job: 'Nurse', hobby: 'Painting'},
        {name: 'Michael', age: '32', city: 'San Francisco', state: 'CA', pets: '1 fish', car: 'Jeep', job: 'Software Developer', hobby: 'Video Games'},
        {name: 'David', age: '28', city: 'Seattle', state: 'WA', pets: '3 dogs', car: 'Volvo', job: 'Journalist', hobby: 'Surfing'},
        {name: 'Emily', age: '36', city: 'Washington', state: 'DC', pets: 'No pets', car: 'Lexus', job: 'Artist', hobby: 'Reading'},
        {name: 'John', age: '22', city: 'New York', state: 'NY', pets: 'No pets', car: 'Audi', job: 'Developer', hobby: 'Gardening'},
        {name: 'Susan', age: '45', city: 'Los Angeles', state: 'CA', pets: '3 cats', car: 'Honda', job: 'Lawyer', hobby: 'Yoga'},
        {name: 'Luke', age: '34', city: 'Chicago', state: 'IL', pets: '2 dogs', car: 'Ford', job: 'Doctor', hobby: 'Swimming'},
        {name: 'Jack', age: '25', city: 'Houston', state: 'TX', pets: 'No pets', car: 'Chevy', job: 'Teacher', hobby: 'Photography'},
        {name: 'Anna', age: '41', city: 'Philadelphia', state: 'PA', pets: '1 bird', car: 'Toyota', job: 'Engineer', hobby: 'Travelling'},
        {name: 'Tom', age: '19', city: 'San Diego', state: 'CA', pets: '2 hamsters', car: 'BMW', job: 'Accountant', hobby: 'Hiking'},
        {name: 'Alice', age: '38', city: 'Phoenix', state: 'AZ', pets: 'No pets', car: 'Tesla', job: 'Nurse', hobby: 'Painting'},
        {name: 'Michael', age: '32', city: 'San Francisco', state: 'CA', pets: '1 fish', car: 'Jeep', job: 'Software Developer', hobby: 'Video Games'},
        {name: 'David', age: '28', city: 'Seattle', state: 'WA', pets: '3 dogs', car: 'Volvo', job: 'Journalist', hobby: 'Surfing'},
        {name: 'Emily', age: '36', city: 'Washington', state: 'DC', pets: 'No pets', car: 'Lexus', job: 'Artist', hobby: 'Reading'},
        {name: 'John', age: '22', city: 'New York', state: 'NY', pets: 'No pets', car: 'Audi', job: 'Developer', hobby: 'Gardening'},
        {name: 'Susan', age: '45', city: 'Los Angeles', state: 'CA', pets: '3 cats', car: 'Honda', job: 'Lawyer', hobby: 'Yoga'},
        {name: 'Luke', age: '34', city: 'Chicago', state: 'IL', pets: '2 dogs', car: 'Ford', job: 'Doctor', hobby: 'Swimming'},
        {name: 'Jack', age: '25', city: 'Houston', state: 'TX', pets: 'No pets', car: 'Chevy', job: 'Teacher', hobby: 'Photography'},
        {name: 'Anna', age: '41', city: 'Philadelphia', state: 'PA', pets: '1 bird', car: 'Toyota', job: 'Engineer', hobby: 'Travelling'},
        {name: 'Tom', age: '19', city: 'San Diego', state: 'CA', pets: '2 hamsters', car: 'BMW', job: 'Accountant', hobby: 'Hiking'},
        {name: 'Alice', age: '38', city: 'Phoenix', state: 'AZ', pets: 'No pets', car: 'Tesla', job: 'Nurse', hobby: 'Painting'},
        {name: 'Michael', age: '32', city: 'San Francisco', state: 'CA', pets: '1 fish', car: 'Jeep', job: 'Software Developer', hobby: 'Video Games'},
        {name: 'David', age: '28', city: 'Seattle', state: 'WA', pets: '3 dogs', car: 'Volvo', job: 'Journalist', hobby: 'Surfing'},
        {name: 'Emily', age: '36', city: 'Washington', state: 'DC', pets: 'No pets', car: 'Lexus', job: 'Artist', hobby: 'Reading'},
        {name: 'John', age: '22', city: 'New York', state: 'NY', pets: 'No pets', car: 'Audi', job: 'Developer', hobby: 'Gardening'},
        {name: 'Susan', age: '45', city: 'Los Angeles', state: 'CA', pets: '3 cats', car: 'Honda', job: 'Lawyer', hobby: 'Yoga'},
        {name: 'Luke', age: '34', city: 'Chicago', state: 'IL', pets: '2 dogs', car: 'Ford', job: 'Doctor', hobby: 'Swimming'},
        {name: 'Jack', age: '25', city: 'Houston', state: 'TX', pets: 'No pets', car: 'Chevy', job: 'Teacher', hobby: 'Photography'},
        {name: 'Anna', age: '41', city: 'Philadelphia', state: 'PA', pets: '1 bird', car: 'Toyota', job: 'Engineer', hobby: 'Travelling'},
        {name: 'Tom', age: '19', city: 'San Diego', state: 'CA', pets: '2 hamsters', car: 'BMW', job: 'Accountant', hobby: 'Hiking'},
        {name: 'Alice', age: '38', city: 'Phoenix', state: 'AZ', pets: 'No pets', car: 'Tesla', job: 'Nurse', hobby: 'Painting'},
        {name: 'Michael', age: '32', city: 'San Francisco', state: 'CA', pets: '1 fish', car: 'Jeep', job: 'Software Developer', hobby: 'Video Games'},
        {name: 'David', age: '28', city: 'Seattle', state: 'WA', pets: '3 dogs', car: 'Volvo', job: 'Journalist', hobby: 'Surfing'},
        {name: 'Emily', age: '36', city: 'Washington', state: 'DC', pets: 'No pets', car: 'Lexus', job: 'Artist', hobby: 'Reading'},
        {name: 'John', age: '22', city: 'New York', state: 'NY', pets: 'No pets', car: 'Audi', job: 'Developer', hobby: 'Gardening'},
        {name: 'Susan', age: '45', city: 'Los Angeles', state: 'CA', pets: '3 cats', car: 'Honda', job: 'Lawyer', hobby: 'Yoga'},
        {name: 'Luke', age: '34', city: 'Chicago', state: 'IL', pets: '2 dogs', car: 'Ford', job: 'Doctor', hobby: 'Swimming'},
        {name: 'Jack', age: '25', city: 'Houston', state: 'TX', pets: 'No pets', car: 'Chevy', job: 'Teacher', hobby: 'Photography'},
        {name: 'Anna', age: '41', city: 'Philadelphia', state: 'PA', pets: '1 bird', car: 'Toyota', job: 'Engineer', hobby: 'Travelling'},
        {name: 'Tom', age: '19', city: 'San Diego', state: 'CA', pets: '2 hamsters', car: 'BMW', job: 'Accountant', hobby: 'Hiking'},
        {name: 'Alice', age: '38', city: 'Phoenix', state: 'AZ', pets: 'No pets', car: 'Tesla', job: 'Nurse', hobby: 'Painting'},
        {name: 'Michael', age: '32', city: 'San Francisco', state: 'CA', pets: '1 fish', car: 'Jeep', job: 'Software Developer', hobby: 'Video Games'},
        {name: 'David', age: '28', city: 'Seattle', state: 'WA', pets: '3 dogs', car: 'Volvo', job: 'Journalist', hobby: 'Surfing'},
        {name: 'Emily', age: '36', city: 'Washington', state: 'DC', pets: 'No pets', car: 'Lexus', job: 'Artist', hobby: 'Reading'},
        {name: 'John', age: '22', city: 'New York', state: 'NY', pets: 'No pets', car: 'Audi', job: 'Developer', hobby: 'Gardening'},
        {name: 'Susan', age: '45', city: 'Los Angeles', state: 'CA', pets: '3 cats', car: 'Honda', job: 'Lawyer', hobby: 'Yoga'},
        {name: 'Luke', age: '34', city: 'Chicago', state: 'IL', pets: '2 dogs', car: 'Ford', job: 'Doctor', hobby: 'Swimming'},
        {name: 'Jack', age: '25', city: 'Houston', state: 'TX', pets: 'No pets', car: 'Chevy', job: 'Teacher', hobby: 'Photography'},
        {name: 'Anna', age: '41', city: 'Philadelphia', state: 'PA', pets: '1 bird', car: 'Toyota', job: 'Engineer', hobby: 'Travelling'},
        {name: 'Tom', age: '19', city: 'San Diego', state: 'CA', pets: '2 hamsters', car: 'BMW', job: 'Accountant', hobby: 'Hiking'},
        {name: 'Alice', age: '38', city: 'Phoenix', state: 'AZ', pets: 'No pets', car: 'Tesla', job: 'Nurse', hobby: 'Painting'},
        {name: 'Michael', age: '32', city: 'San Francisco', state: 'CA', pets: '1 fish', car: 'Jeep', job: 'Software Developer', hobby: 'Video Games'},
        {name: 'David', age: '28', city: 'Seattle', state: 'WA', pets: '3 dogs', car: 'Volvo', job: 'Journalist', hobby: 'Surfing'},
        {name: 'Emily', age: '36', city: 'Washington', state: 'DC', pets: 'No pets', car: 'Lexus', job: 'Artist', hobby: 'Reading'},
        {name: 'John', age: '22', city: 'New York', state: 'NY', pets: 'No pets', car: 'Audi', job: 'Developer', hobby: 'Gardening'},
        {name: 'Susan', age: '45', city: 'Los Angeles', state: 'CA', pets: '3 cats', car: 'Honda', job: 'Lawyer', hobby: 'Yoga'},
        {name: 'Luke', age: '34', city: 'Chicago', state: 'IL', pets: '2 dogs', car: 'Ford', job: 'Doctor', hobby: 'Swimming'},
        {name: 'Jack', age: '25', city: 'Houston', state: 'TX', pets: 'No pets', car: 'Chevy', job: 'Teacher', hobby: 'Photography'},
        {name: 'Anna', age: '41', city: 'Philadelphia', state: 'PA', pets: '1 bird', car: 'Toyota', job: 'Engineer', hobby: 'Travelling'},
        {name: 'Tom', age: '19', city: 'San Diego', state: 'CA', pets: '2 hamsters', car: 'BMW', job: 'Accountant', hobby: 'Hiking'},
        {name: 'Alice', age: '38', city: 'Phoenix', state: 'AZ', pets: 'No pets', car: 'Tesla', job: 'Nurse', hobby: 'Painting'},
        {name: 'Michael', age: '32', city: 'San Francisco', state: 'CA', pets: '1 fish', car: 'Jeep', job: 'Software Developer', hobby: 'Video Games'},
        {name: 'David', age: '28', city: 'Seattle', state: 'WA', pets: '3 dogs', car: 'Volvo', job: 'Journalist', hobby: 'Surfing'},
        {name: 'Emily', age: '36', city: 'Washington', state: 'DC', pets: 'No pets', car: 'Lexus', job: 'Artist', hobby: 'Reading'},
    ]
};

window.onload = function() {
    let table = new IrTableClassic(tableData.rows, tableData.columns);
    document.body.appendChild(table.getHtml());
}